### ISSUE TITLE
Middleware fails with Django 1.10

### ISSUE THREAD

**Issue by huwshimi** [opbeat/opbeat_python#120]
If I use the `OpbeatAPMMiddleware` middleware with the new `MIDDLEWARE = [...]` setting then any view fails with:

```
Traceback (most recent call last):
  File "home/username/project/test_file.py", line 353, in test_file
    HTTP_HOST='subdomain.example.com'
  File "home/username/project/env/local/lib/python2.7/site-packages/django/test/client.py", line 541, in post
    secure=secure, **extra)
  File "home/username/project/env/local/lib/python2.7/site-packages/django/test/client.py", line 343, in post
    secure=secure, **extra)
  File "home/username/project/env/local/lib/python2.7/site-packages/django/test/client.py", line 409, in generic
    return self.request(**r)
  File "home/username/project/env/local/lib/python2.7/site-packages/django/test/client.py", line 476, in request
    response = self.handler(environ)
  File "home/username/project/env/local/lib/python2.7/site-packages/django/test/client.py", line 129, in __call__
    self.load_middleware()
  File "home/username/project/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: __init__() takes exactly 1 argument (2 given)

```

I believe the middleware may need updating to be compatible with Django 1.10: https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware

**Comment by piquadrat** [comment]
Thanks for the report! Unfortunately, we couldn't finish support for Django 1.10 just yet. We hope to release an update soon.

**Comment by piquadrat** [comment]
@huwshimi we just pushed version 3.4 of the Opbeat module to PyPI, with support for Django 1.10. Can you give it a try?

**Comment by huwshimi** [comment]
@piquadrat thanks heaps! I'll give it a go.
