### ISSUE TITLE
Trying to `pop` from empty `trace_stack`

### ISSUE THREAD

**Issue by rossgray** [opbeat/opbeat_python#144]
Hi,

I get the following exception from various points in our code when our Flask application is under medium load:

```
trace = self.trace_stack.pop()
IndexError: pop from empty list
```

We are running **Python 3.5.2 / Flask 0.11.1 / Opbeat 3.5.1**

A full stack trace example:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1644, in full_dispatch_request
request_finished.send(self, response=response)
File "/usr/local/lib/python3.5/site-packages/blinker/base.py", line 267, in send
for receiver in self.receivers_for(sender)]
File "/usr/local/lib/python3.5/site-packages/blinker/base.py", line 267, in <listcomp>
for receiver in self.receivers_for(sender)]
File "/usr/local/lib/python3.5/site-packages/opbeat/contrib/flask/__init__.py", line 207, in request_finished
self.client.end_transaction(rule, response.status_code)
File "/usr/local/lib/python3.5/site-packages/opbeat/base.py", line 589, in end_transaction
self.instrumentation_store.transaction_end(status_code, name)
File "/usr/local/lib/python3.5/site-packages/opbeat/traces.py", line 254, in transaction_end
transaction.end_transaction()
File "/usr/local/lib/python3.5/site-packages/opbeat/traces.py", line 50, in end_transaction
return self.end_trace(skip_frames)
File "/usr/local/lib/python3.5/site-packages/opbeat/traces.py", line 68, in end_trace
trace = self.trace_stack.pop()
IndexError: pop from empty list
```

Could some exception handling be added to the Opbeat client to prevent issues like this breaking our application? It seems related to an older, resolved issue: #53 

If you need any more information please let me know.

Thanks

**Comment by piquadrat** [comment]
Hi @rossgray :)

Thanks for opening the issue! We were able to replicate it, and currently suspect a threading issue to be the cause of it. A workaround for now might be to avoid using threaded WSGI servers and instead use multiple worker processes.
