### ISSUE TITLE
PGConnectionProxy & JSONField problem

### ISSUE THREAD

**Issue by msgre** [opbeat/opbeat_python#152]
Hi,
we are using OpBeat our Django/PostgreSQL application together with `django-jsonfield` package and it doesn't work. The reason (I believe) is that `conn_or_curs` object passed to `psycopg2` internals is `<class 'opbeat.instrumentation.packages.psycopg2.PGConnectionProxy'>` and not `<connection object>` or cursor.

Full traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.5/site-packages/allauth/account/views.py", line 98, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/allauth/account/views.py", line 66, in dispatch
    **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/generic/edit.py", line 213, in get
    return self.render_to_response(self.get_context_data())
  File "/usr/local/lib/python3.5/site-packages/allauth/account/views.py", line 129, in get_context_data
    site = get_current_site(self.request)
  File "/usr/local/lib/python3.5/site-packages/allauth/utils.py", line 155, in get_current_site
    site = Site.objects.get_current(request=request)
  File "/usr/local/lib/python3.5/site-packages/django/contrib/sites/models.py", line 65, in get_current
    return self._get_site_by_id(site_id)
  File "/usr/local/lib/python3.5/site-packages/django/contrib/sites/models.py", line 35, in _get_site_by_id
    site = self.get(pk=site_id)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 381, in get
    num = len(clone)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 233, in cursor
    cursor = self.make_cursor(self._cursor())
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 174, in connect
    connection_created.send(sender=self.__class__, connection=self)
  File "/usr/local/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.5/site-packages/jsonfield/fields.py", line 167, in configure_database_connection
    loads=lambda x: x)
  File "/usr/local/lib/python3.5/site-packages/psycopg2/_json.py", line 174, in register_default_jsonb
    loads=loads, oid=JSONB_OID, array_oid=JSONBARRAY_OID, name='jsonb')
  File "/usr/local/lib/python3.5/site-packages/psycopg2/_json.py", line 145, in register_json
    register_type(JSON, not globally and conn_or_curs or None)
TypeError: argument 2 must be a connection, cursor or None
```

Versions:

```
Django==1.9.7
django-jsonfield==1.0.1
psycopg2==2.6.2
opbeat==3.3.4
```

**Comment by piquadrat** [comment]
Hi @msgre :) Can you try and upgrade to the latest version of Opbeat? This issue should have been fixed in 6184b477e4, which was released in version 3.5 of the module.

**Comment by msgre** [comment]
Hi @piquadrat, I could confirm that with `opbeat==3.5.2` our app works again. Thank you very much for help!

**Comment by piquadrat** [comment]
Awesome :)

**Comment by dmarcelino** [comment]
Thanks!
