### ISSUE TITLE
Errors running under Apache mod_wsgi in AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by techdragon** [opbeat/opbeat_python#153]
Opbeat works correctly in local dev with debug turned on. But the module generates a FileNotFound error. This prevents pages from loading. This may need some kind of bypass setting to avoid triggering the problem since I can see why the uwsgi code is needed for checking the master pid.

```
[Mon Feb 27 00:03:12.383429 2017] [:error] [pid 4644] mod_wsgi (pid=4644): Exception occurred within exit functions.
[Mon Feb 27 00:03:12.383488 2017] [:error] [pid 4644] Traceback (most recent call last):
[Mon Feb 27 00:03:12.383728 2017] [:error] [pid 4644]   File "/opt/python/run/venv/lib64/python3.4/site-packages/opbeat/base.py", line 460, in send_remote
[Mon Feb 27 00:03:12.383735 2017] [:error] [pid 4644]     self._send_remote(url=url, data=data, headers=headers)
[Mon Feb 27 00:03:12.383762 2017] [:error] [pid 4644]   File "/opt/python/run/venv/lib64/python3.4/site-packages/opbeat/base.py", line 405, in _send_remote
[Mon Feb 27 00:03:12.383766 2017] [:error] [pid 4644]     transport = self._get_transport(parsed)
[Mon Feb 27 00:03:12.383784 2017] [:error] [pid 4644]   File "/opt/python/run/venv/lib64/python3.4/site-packages/opbeat/base.py", line 427, in _get_transport
[Mon Feb 27 00:03:12.383788 2017] [:error] [pid 4644]     if self.async_mode and is_master_process():
[Mon Feb 27 00:03:12.383885 2017] [:error] [pid 4644]   File "/opt/python/run/venv/lib64/python3.4/site-packages/opbeat/utils/__init__.py", line 77, in is_master_process
[Mon Feb 27 00:03:12.383891 2017] [:error] [pid 4644]     import uwsgi
[Mon Feb 27 00:03:12.383906 2017] [:error] [pid 4644]   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
[Mon Feb 27 00:03:12.383918 2017] [:error] [pid 4644]   File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
[Mon Feb 27 00:03:12.383929 2017] [:error] [pid 4644]   File "<frozen importlib._bootstrap>", line 2164, in _find_spec
[Mon Feb 27 00:03:12.383938 2017] [:error] [pid 4644]   File "<frozen importlib._bootstrap>", line 1940, in find_spec
[Mon Feb 27 00:03:12.383948 2017] [:error] [pid 4644]   File "<frozen importlib._bootstrap>", line 1911, in _get_spec
[Mon Feb 27 00:03:12.383958 2017] [:error] [pid 4644]   File "<frozen importlib._bootstrap>", line 1879, in _path_importer_cache
[Mon Feb 27 00:03:12.383979 2017] [:error] [pid 4644] FileNotFoundError: [Errno 2] No such file or directory
[Mon Feb 27 00:03:12.383988 2017] [:error] [pid 4644]
[Mon Feb 27 00:03:12.383991 2017] [:error] [pid 4644] During handling of the above exception, another exception occurred:
[Mon Feb 27 00:03:12.383992 2017] [:error] [pid 4644]
[Mon Feb 27 00:03:12.383999 2017] [:error] [pid 4644] Traceback (most recent call last):
[Mon Feb 27 00:03:12.384025 2017] [:error] [pid 4644]   File "/opt/python/run/venv/lib64/python3.4/site-packages/opbeat/base.py", line 594, in close
[Mon Feb 27 00:03:12.384029 2017] [:error] [pid 4644]     self._traces_collect()
[Mon Feb 27 00:03:12.384048 2017] [:error] [pid 4644]   File "/opt/python/run/venv/lib64/python3.4/site-packages/opbeat/base.py", line 635, in _traces_collect
[Mon Feb 27 00:03:12.384051 2017] [:error] [pid 4644]     self.send(**data)
[Mon Feb 27 00:03:12.384199 2017] [:error] [pid 4644]   File "/opt/python/run/venv/lib64/python3.4/site-packages/opbeat/contrib/django/client.py", line 213, in send
[Mon Feb 27 00:03:12.384205 2017] [:error] [pid 4644]     return super(DjangoClient, self).send(**kwargs)
[Mon Feb 27 00:03:12.384226 2017] [:error] [pid 4644]   File "/opt/python/run/venv/lib64/python3.4/site-packages/opbeat/base.py", line 478, in send
[Mon Feb 27 00:03:12.384230 2017] [:error] [pid 4644]     servers=servers)
[Mon Feb 27 00:03:12.384259 2017] [:error] [pid 4644]   File "/opt/python/run/venv/lib64/python3.4/site-packages/opbeat/base.py", line 506, in send_encoded
[Mon Feb 27 00:03:12.384267 2017] [:error] [pid 4644]     self.send_remote(url=url, data=message, headers=headers)
[Mon Feb 27 00:03:12.384285 2017] [:error] [pid 4644]   File "/opt/python/run/venv/lib64/python3.4/site-packages/opbeat/base.py", line 462, in send_remote
[Mon Feb 27 00:03:12.384288 2017] [:error] [pid 4644]     self.handle_transport_fail(exception=e)
[Mon Feb 27 00:03:12.384305 2017] [:error] [pid 4644]   File "/opt/python/run/venv/lib64/python3.4/site-packages/opbeat/base.py", line 611, in handle_transport_fail
[Mon Feb 27 00:03:12.384307 2017] [:error] [pid 4644]     message = self._get_log_message(exception.data)
[Mon Feb 27 00:03:12.384321 2017] [:error] [pid 4644] AttributeError: 'FileNotFoundError' object has no attribute 'data'
```

`ASYNC: False` fails with a different error.

```
[Sun Feb 26 23:49:08.931015 2017] [:error] [pid 3800] Unable to reach Opbeat server: ('Connection aborted.', BadStatusLine("''",)) (url: https://intake.opbeat.com/api/v1/organizations/<my_org_id>/apps/<my_app_id>/errors/)
[Sun Feb 26 23:49:08.937774 2017] [:error] [pid 3800] Failed to submit message: "PermissionError: [Errno 13] Permission denied: '/opt/python/current/app/static/sass/app.css'"
[Sun Feb 26 23:49:08.937784 2017] [:error] [pid 3800] Traceback (most recent call last):
[Sun Feb 26 23:49:08.937787 2017] [:error] [pid 3800]   File "/opt/python/run/venv/lib/python3.4/site-packages/urllib3/connectionpool.py", line 600, in urlopen
[Sun Feb 26 23:49:08.937789 2017] [:error] [pid 3800]     chunked=chunked)
[Sun Feb 26 23:49:08.937791 2017] [:error] [pid 3800]   File "/opt/python/run/venv/lib/python3.4/site-packages/urllib3/connectionpool.py", line 386, in _make_request
[Sun Feb 26 23:49:08.937793 2017] [:error] [pid 3800]     six.raise_from(e, None)
[Sun Feb 26 23:49:08.937795 2017] [:error] [pid 3800]   File "<string>", line 2, in raise_from
[Sun Feb 26 23:49:08.937797 2017] [:error] [pid 3800]   File "/opt/python/run/venv/lib/python3.4/site-packages/urllib3/connectionpool.py", line 382, in _make_request
[Sun Feb 26 23:49:08.937799 2017] [:error] [pid 3800]     httplib_response = conn.getresponse()
[Sun Feb 26 23:49:08.937801 2017] [:error] [pid 3800]   File "/usr/lib64/python3.4/http/client.py", line 1208, in getresponse
[Sun Feb 26 23:49:08.937802 2017] [:error] [pid 3800]     response.begin()
[Sun Feb 26 23:49:08.937804 2017] [:error] [pid 3800]   File "/usr/lib64/python3.4/http/client.py", line 380, in begin
[Sun Feb 26 23:49:08.937806 2017] [:error] [pid 3800]     version, status, reason = self._read_status()
[Sun Feb 26 23:49:08.937808 2017] [:error] [pid 3800]   File "/usr/lib64/python3.4/http/client.py", line 350, in _read_status
[Sun Feb 26 23:49:08.937810 2017] [:error] [pid 3800]     raise BadStatusLine(line)
[Sun Feb 26 23:49:08.937812 2017] [:error] [pid 3800] http.client.BadStatusLine: ''
[Sun Feb 26 23:49:08.937814 2017] [:error] [pid 3800] 
[Sun Feb 26 23:49:08.937816 2017] [:error] [pid 3800] During handling of the above exception, another exception occurred:
[Sun Feb 26 23:49:08.937818 2017] [:error] [pid 3800] 
[Sun Feb 26 23:49:08.937819 2017] [:error] [pid 3800] Traceback (most recent call last):
[Sun Feb 26 23:49:08.937821 2017] [:error] [pid 3800]   File "/opt/python/run/venv/lib64/python3.4/site-packages/opbeat/transport/http_urllib3.py", line 37, in send
[Sun Feb 26 23:49:08.937823 2017] [:error] [pid 3800]     'POST', self._url, body=data, headers=headers, timeout=timeout
[Sun Feb 26 23:49:08.937825 2017] [:error] [pid 3800]   File "/opt/python/run/venv/lib/python3.4/site-packages/urllib3/poolmanager.py", line 244, in urlopen
[Sun Feb 26 23:49:08.937833 2017] [:error] [pid 3800]     response = conn.urlopen(method, u.request_uri, **kw)
[Sun Feb 26 23:49:08.937835 2017] [:error] [pid 3800]   File "/opt/python/run/venv/lib64/python3.4/site-packages/opbeat/instrumentation/packages/base.py", line 63, in __call__
[Sun Feb 26 23:49:08.937837 2017] [:error] [pid 3800]     args, kwargs)
[Sun Feb 26 23:49:08.937839 2017] [:error] [pid 3800]   File "/opt/python/run/venv/lib64/python3.4/site-packages/opbeat/instrumentation/packages/base.py", line 222, in call_if_sampling
[Sun Feb 26 23:49:08.937841 2017] [:error] [pid 3800]     return self.call(module, method, wrapped, instance, args, kwargs)
[Sun Feb 26 23:49:08.937843 2017] [:error] [pid 3800]   File "/opt/python/run/venv/lib64/python3.4/site-packages/opbeat/instrumentation/packages/urllib3.py", line 35, in call
[Sun Feb 26 23:49:08.937844 2017] [:error] [pid 3800]     return wrapped(*args, **kwargs)
[Sun Feb 26 23:49:08.937846 2017] [:error] [pid 3800]   File "/opt/python/run/venv/lib/python3.4/site-packages/urllib3/connectionpool.py", line 649, in urlopen
[Sun Feb 26 23:49:08.937848 2017] [:error] [pid 3800]     _stacktrace=sys.exc_info()[2])
[Sun Feb 26 23:49:08.937849 2017] [:error] [pid 3800]   File "/opt/python/run/venv/lib/python3.4/site-packages/urllib3/util/retry.py", line 347, in increment
[Sun Feb 26 23:49:08.937851 2017] [:error] [pid 3800]     raise six.reraise(type(error), error, _stacktrace)
[Sun Feb 26 23:49:08.937853 2017] [:error] [pid 3800]   File "/opt/python/run/venv/lib/python3.4/site-packages/urllib3/packages/six.py", line 685, in reraise
[Sun Feb 26 23:49:08.937854 2017] [:error] [pid 3800]     raise value.with_traceback(tb)
[Sun Feb 26 23:49:08.937856 2017] [:error] [pid 3800]   File "/opt/python/run/venv/lib/python3.4/site-packages/urllib3/connectionpool.py", line 600, in urlopen
[Sun Feb 26 23:49:08.937858 2017] [:error] [pid 3800]     chunked=chunked)
[Sun Feb 26 23:49:08.937859 2017] [:error] [pid 3800]   File "/opt/python/run/venv/lib/python3.4/site-packages/urllib3/connectionpool.py", line 386, in _make_request
[Sun Feb 26 23:49:08.937861 2017] [:error] [pid 3800]     six.raise_from(e, None)
[Sun Feb 26 23:49:08.937863 2017] [:error] [pid 3800]   File "<string>", line 2, in raise_from
[Sun Feb 26 23:49:08.937864 2017] [:error] [pid 3800]   File "/opt/python/run/venv/lib/python3.4/site-packages/urllib3/connectionpool.py", line 382, in _make_request
[Sun Feb 26 23:49:08.937866 2017] [:error] [pid 3800]     httplib_response = conn.getresponse()
[Sun Feb 26 23:49:08.937868 2017] [:error] [pid 3800]   File "/usr/lib64/python3.4/http/client.py", line 1208, in getresponse
[Sun Feb 26 23:49:08.937869 2017] [:error] [pid 3800]     response.begin()
[Sun Feb 26 23:49:08.937871 2017] [:error] [pid 3800]   File "/usr/lib64/python3.4/http/client.py", line 380, in begin
[Sun Feb 26 23:49:08.937873 2017] [:error] [pid 3800]     version, status, reason = self._read_status()
[Sun Feb 26 23:49:08.937874 2017] [:error] [pid 3800]   File "/usr/lib64/python3.4/http/client.py", line 350, in _read_status
[Sun Feb 26 23:49:08.937876 2017] [:error] [pid 3800]     raise BadStatusLine(line)
[Sun Feb 26 23:49:08.937878 2017] [:error] [pid 3800] urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine("''",))
[Sun Feb 26 23:49:08.937879 2017] [:error] [pid 3800] 
[Sun Feb 26 23:49:08.937881 2017] [:error] [pid 3800] During handling of the above exception, another exception occurred:
[Sun Feb 26 23:49:08.937882 2017] [:error] [pid 3800] 
[Sun Feb 26 23:49:08.937884 2017] [:error] [pid 3800] Traceback (most recent call last):
[Sun Feb 26 23:49:08.937885 2017] [:error] [pid 3800]   File "/opt/python/run/venv/lib64/python3.4/site-packages/opbeat/base.py", line 460, in send_remote
[Sun Feb 26 23:49:08.937887 2017] [:error] [pid 3800]     self._send_remote(url=url, data=data, headers=headers)
[Sun Feb 26 23:49:08.937889 2017] [:error] [pid 3800]   File "/opt/python/run/venv/lib64/python3.4/site-packages/opbeat/base.py", line 413, in _send_remote
[Sun Feb 26 23:49:08.937891 2017] [:error] [pid 3800]     url = transport.send(data, headers, timeout=self.timeout)
[Sun Feb 26 23:49:08.937895 2017] [:error] [pid 3800]   File "/opt/python/run/venv/lib64/python3.4/site-packages/opbeat/transport/http_urllib3.py", line 51, in send
[Sun Feb 26 23:49:08.937897 2017] [:error] [pid 3800]     raise TransportException(message, data, print_trace=print_trace)
[Sun Feb 26 23:49:08.937899 2017] [:error] [pid 3800] opbeat.transport.base.TransportException: Unable to reach Opbeat server: ('Connection aborted.', BadStatusLine("''",)) (url: https://intake.opbeat.com/api/v1/organizations/<my_org_id>/apps/<my_app_id>/errors/)
[Sun Feb 26 23:49:08.937904 2017] [:error] [pid 3800] 
```

**Comment by piquadrat** [comment]
Hi @techdragon. I have to admit, I'm a bit confused. Importing a non-existing module shouldn't raise a `FileNotFoundError`, but an `ImportError`.

Google led me to this issue on the Python bugtracker: https://bugs.python.org/issue22834. The gist of it seems to be that `importlib` didn't like if the current directory got deleted during the lifetime of the process. Is something like this happening in your case?

Unfortunately, I don't think there is much we can do on our side to fix this.

**Comment by techdragon** [comment]
@piquadrat I've opened #154 with a possible fix. I've tested it in The same AWS Elastic Beanstalk environment that produced the original errors, and it seems to now work as intended.
